# -*- coding: utf-8 -*-
"""Number Analyzer System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tz6Z2w0PQHV4UtfZ_ZUM7w42kOl55uXE
"""

def check_number(num):
    if num > 0:
        print(num ," is Positive")
    elif num == 0:
        print(num ," is Zero")
    else:
        print(num ," is Negative")

def even_or_odd(num):
    if num % 2 == 0:
        print(num ," is Even")
    else:
        print(num ," is Odd")

def prime(num):
  if num > 1:
    for i in range(2, num):
        if (num % i) == 0:
            print(num, " is not a prime number")
            break
    else:
        print(num, " is a prime number")

def palindrome(num):
  palin = 0
  temp = num
  while temp > 0:
    digit = temp % 10
    palin = palin * 10 + digit
    temp = temp // 10
  if num == palin:
    print(num ," is Palindrome")
  else:
    print(num ," is not Palindrome")

def leap_year(num):
  if (num % 4 == 0 and num % 100 != 0) or (num % 400 == 0):
    print(num ," is Leap Year")
  else:
    print(num ," is not Leap Year")

def armstrong(num):
  sum = 0
  temp = num
  power = len(str(num))
  while temp > 0:
    digit = temp % 10
    sum = digit ** power
    temp = temp // 10
  if sum == num:
    print(num ," is armstrong number")
  else:
    print(num ," is not armstrong number")

def pronic_number(num):
  for i in range(num + 1):
    n = i * (i + 1)
    if n == num:
      print(num ," is pronic number")
      break
  else:
    print(num ," is not pronic number")

def sum_of_digits(num):
  sum = 0
  while num > 0:
    digit = num % 10
    sum = sum + digit
    num = num // 10
  print(sum ," is sum of digits")

def reverse(num):
  rev = 0
  temp = num
  while temp > 0:
    digit = temp % 10
    rev = rev * 10 + digit
    temp = temp // 10
  print(rev ," is reverse")

def count_digits(num):
  count = 0
  temp = num
  while temp > 0:
    temp = temp // 10
    count = count + 1
  print(count ," is count of digits")

def factorial(num):
  fact = 1
  for i in range(1, num + 1):
    fact = fact * i
  print(fact ," is factorial value")

def perfect_number(num):
  sum = 0
  for i in range(1, num):
    if num % i == 0:
      sum = sum + i
  if sum == num:
    print(num ," is perfect number")
  else:
    print(num ," is not perfect number")

def harshad_number(num):
  sum = 0
  temp = num
  while temp > 0:
    digit = temp % 10
    sum = sum + digit
    temp = temp // 10
  if num % sum == 0:
    print(num ," is harshad number")
  else:
    print(num ," is not harshad number")

def factors(num):
  lst = []
  for i in range(1, num + 1):
    if num % i == 0:
      lst.append(i)
  print(lst ," are factors")

def main():
  while True:
    num = int(input("Enter the number: "))
    print("\n----- NUMBER ANALYSIS REPORT -----")
    check_number(num)
    even_or_odd(num)
    prime(num)
    palindrome(num)
    leap_year(num)
    armstrong(num)
    pronic_number(num)
    sum_of_digits(num)
    reverse(num)
    count_digits(num)
    factorial(num)
    perfect_number(num)
    harshad_number(num)
    factors(num)
    break

main()